[package]
name = "esta"
version = "0.1.0"
authors = ["epe2 <nedellis1234@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
regex = "1.1.5"
lalrpop-util = "0.16.3"
num-traits = "0.2"
